"""Model checkpoint status + output-provenance vocabulary (framework-agnostic).

This module is deliberately dependency-light (no TensorFlow, no Streamlit) so it
can be imported by the PDF report generator, the Streamlit app, and the tests
without pulling in heavy libraries. It centralizes two honesty-critical ideas:

1. **Checkpoint status.** Whether each model is running on a genuinely loaded
   checkpoint or on random (untrained) weights -- and, crucially, that a loaded
   checkpoint is NOT assumed to be well-trained just because a file exists.

2. **Output provenance.** A single mandated banner and short label used
   everywhere (UI + PDF + stored metadata) so a demonstration output is never
   mistaken for a validated prediction.

Design note: the app currently ships without trained weights, so the normal
state is ``untrained``. The code still models ``loaded`` and ``load_failed``
honestly, because the whole point is to tell the user which one they are looking
at -- and to refuse to silently substitute random weights for a checkpoint that
was present but failed to load.
"""
from __future__ import annotations

from dataclasses import dataclass

# --- Checkpoint states ------------------------------------------------------
STATE_UNTRAINED = "untrained"        # no checkpoint file -> random weights
STATE_LOADED = "loaded"              # a checkpoint file loaded successfully
STATE_LOAD_FAILED = "load_failed"    # a file was present but could not be loaded

# --- Mandated output-provenance copy (swept by the guardrail checks) --------
# Shown for any output produced by random weights OR by the deterministic
# simulated fallback. Uses cautious, non-diagnostic wording only.
DEMO_OUTPUT_BANNER: str = (
    "Demonstration output - no predictive meaning. Generated by an UNTRAINED "
    "model (random weights) to verify software behavior only. Not a prediction, "
    "probability of cancer, risk category, or clinical assessment."
)
LOADED_CHECKPOINT_BANNER: str = (
    "Output produced from a loaded model checkpoint. The application does NOT "
    "verify how that checkpoint was trained or evaluated; treat performance as "
    "unestablished until independently validated. Requires Professional Review."
)

# Short, table-friendly labels (never verdict language).
DEMO_SCORE_LABEL: str = "Demo score (no predictive meaning)"
LOADED_SCORE_LABEL: str = "Model score (checkpoint; provenance unverified)"


@dataclass(frozen=True)
class ModelStatus:
    """The load state of one model, plus honest human-facing wording."""

    name: str                 # e.g. "classifier (EfficientNet-B0)"
    state: str                # one of STATE_* above
    checkpoint: str           # the path we looked for / loaded
    detail: str = ""          # optional extra context (e.g. a load error)

    @property
    def is_trained_source(self) -> bool:
        """True only when a checkpoint actually loaded (still NOT proof of quality)."""
        return self.state == STATE_LOADED

    @property
    def is_demo(self) -> bool:
        """True when outputs carry no predictive meaning (untrained or failed)."""
        return self.state in (STATE_UNTRAINED, STATE_LOAD_FAILED)

    @property
    def banner(self) -> str:
        if self.state == STATE_LOADED:
            return LOADED_CHECKPOINT_BANNER
        return DEMO_OUTPUT_BANNER

    @property
    def score_label(self) -> str:
        return LOADED_SCORE_LABEL if self.state == STATE_LOADED else DEMO_SCORE_LABEL

    def short(self) -> str:
        """One-line status for logs / metadata."""
        human = {
            STATE_UNTRAINED: "untrained (random weights)",
            STATE_LOADED: "loaded checkpoint (provenance unverified)",
            STATE_LOAD_FAILED: "checkpoint present but FAILED to load",
        }.get(self.state, self.state)
        return f"{self.name}: {human}"


def overall_mode(statuses: list[ModelStatus]) -> str:
    """Summarize a set of model statuses into one mode string for reports.

    Any demo/failed model makes the whole analysis a demonstration, because a
    single untrained component means the combined output is not interpretable.
    """
    if not statuses:
        return "unknown"
    if any(s.state == STATE_LOAD_FAILED for s in statuses):
        return "error (a checkpoint failed to load)"
    if all(s.is_trained_source for s in statuses):
        return "loaded checkpoints (provenance unverified by the app)"
    if any(s.is_trained_source for s in statuses):
        return "mixed (some loaded checkpoints, some untrained/demo)"
    return "demonstration (untrained models, random weights)"
